sudo: required
language: node_js

cache:
  directories:
    - node_modules

dist: trusty

jobs:
  include:
    - stage: test
      node_js: lts/*
      script:
        - yarn format
        - yarn build --prefix-paths
    - stage: performance_budget
      node_js: lts/*
      if: type = pull_request
      script: 
        - ./scripts/budget.sh
    - stage: deploy
      if: branch = master
      node_js: lts/*
      script: yarn build --prefix-paths
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $BLOG_TOKEN
        local_dir: public
        on:
          branch: master
