name: CI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: yarn install && yarn global add @lhci/cli@0.7.x
      - run: yarn run build
      - run: lhci autorun
